syntax on
set tabstop=4 softtabstop=4
set shiftwidth=4
set relativenumber
set number
set nohlsearch
set smartindent
set nowrap
set termguicolors
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set splitright
set title
set noerrorbells
set vb t_vb=
"set shellcmdflag=-ic
set pastetoggle=<F4>
set encoding=utf-8
set scrolloff=8
set noshowmode
set cmdheight=1
set showcmd
set path+=**
set wildmenu
set background=dark
set nocompatible
let mapleader=","
